[2021-11-23T11:47:14.040339+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://127.0.0.1:8000/"" at C:\Users\User\Documents\tsi_htmlworkshop\Topic 8\phpproject\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://127.0.0.1:8000/\" at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:182)"} []
[2021-11-23T11:47:14.064288+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T11:47:14.486666+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"c9cb4a"},"request_uri":"http://127.0.0.1:8000/_wdt/c9cb4a","method":"GET"} []
[2021-11-23T11:47:14.980139+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://127.0.0.1:8000/favicon.ico" (from "http://127.0.0.1:8000/")" at C:\Users\User\Documents\tsi_htmlworkshop\Topic 8\phpproject\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://127.0.0.1:8000/favicon.ico\" (from \"http://127.0.0.1:8000/\") at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:70)"} []
[2021-11-23T11:47:15.479197+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T11:47:15.482126+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T11:52:05.092903+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://127.0.0.1:8000/"" at C:\Users\User\Documents\tsi_htmlworkshop\Topic 8\phpproject\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://127.0.0.1:8000/\" at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:182)"} []
[2021-11-23T11:52:05.149240+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T11:52:05.747409+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"3553bf"},"request_uri":"http://127.0.0.1:8000/_wdt/3553bf","method":"GET"} []
[2021-11-23T12:06:39.450404+01:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "[Semantical Error] The annotation "@Route" in method Controller\SynfController::showAction() was never imported. Did you maybe forget to add a "use" statement for this annotation? in C:\Users\User\Documents\tsi_htmlworkshop\Topic 8\phpproject\config/routes\../../src/Controller/ (which is being imported from "C:\Users\User\Documents\tsi_htmlworkshop\Topic 8\phpproject\config/routes/annotations.yaml"). Make sure to use PHP 8+ or that annotations are installed and enabled." at C:\Users\User\Documents\tsi_htmlworkshop\Topic 8\phpproject\vendor\symfony\config\Loader\FileLoader.php line 174 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): [Semantical Error] The annotation \"@Route\" in method Controller\\SynfController::showAction() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? in C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\config/routes\\../../src/Controller/ (which is being imported from \"C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\config/routes/annotations.yaml\"). Make sure to use PHP 8+ or that annotations are installed and enabled. at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\symfony\\config\\Loader\\FileLoader.php:174)\n[previous exception] [object] (Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Semantical Error] The annotation \"@Route\" in method Controller\\SynfController::showAction() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\annotations\\lib\\Doctrine\\Common\\Annotations\\AnnotationException.php:39)"} []
[2021-11-23T12:06:39.656634+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T12:06:39.668616+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:13:54.911120+01:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "[Semantical Error] The annotation "@Route" in method Controller\SynfController::showAction() was never imported. Did you maybe forget to add a "use" statement for this annotation? in C:\Users\User\Documents\tsi_htmlworkshop\Topic 8\phpproject\config/routes\../../src/Controller/ (which is being imported from "C:\Users\User\Documents\tsi_htmlworkshop\Topic 8\phpproject\config/routes/annotations.yaml"). Make sure to use PHP 8+ or that annotations are installed and enabled." at C:\Users\User\Documents\tsi_htmlworkshop\Topic 8\phpproject\vendor\symfony\config\Loader\FileLoader.php line 174 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): [Semantical Error] The annotation \"@Route\" in method Controller\\SynfController::showAction() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? in C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\config/routes\\../../src/Controller/ (which is being imported from \"C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\config/routes/annotations.yaml\"). Make sure to use PHP 8+ or that annotations are installed and enabled. at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\symfony\\config\\Loader\\FileLoader.php:174)\n[previous exception] [object] (Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Semantical Error] The annotation \"@Route\" in method Controller\\SynfController::showAction() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\annotations\\lib\\Doctrine\\Common\\Annotations\\AnnotationException.php:39)"} []
[2021-11-23T14:13:55.145368+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:13:55.155306+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:13:55.554311+01:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "[Semantical Error] The annotation "@Route" in method Controller\SynfController::showAction() was never imported. Did you maybe forget to add a "use" statement for this annotation? in C:\Users\User\Documents\tsi_htmlworkshop\Topic 8\phpproject\config/routes\../../src/Controller/ (which is being imported from "C:\Users\User\Documents\tsi_htmlworkshop\Topic 8\phpproject\config/routes/annotations.yaml"). Make sure to use PHP 8+ or that annotations are installed and enabled." at C:\Users\User\Documents\tsi_htmlworkshop\Topic 8\phpproject\vendor\symfony\config\Loader\FileLoader.php line 174 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): [Semantical Error] The annotation \"@Route\" in method Controller\\SynfController::showAction() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? in C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\config/routes\\../../src/Controller/ (which is being imported from \"C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\config/routes/annotations.yaml\"). Make sure to use PHP 8+ or that annotations are installed and enabled. at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\symfony\\config\\Loader\\FileLoader.php:174)\n[previous exception] [object] (Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Semantical Error] The annotation \"@Route\" in method Controller\\SynfController::showAction() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\annotations\\lib\\Doctrine\\Common\\Annotations\\AnnotationException.php:39)"} []
[2021-11-23T14:13:55.777149+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:13:55.783604+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:14:24.028214+01:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://127.0.0.1:8000/lucky/number","method":"GET"} []
[2021-11-23T14:14:24.033257+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-11-23T14:14:24.099692+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:14:24.423513+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"3da8b7"},"request_uri":"http://127.0.0.1:8000/_wdt/3da8b7","method":"GET"} []
[2021-11-23T14:18:01.193075+01:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://127.0.0.1:8000/lucky/number","method":"GET"} []
[2021-11-23T14:18:01.202832+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-11-23T14:18:01.289193+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:18:01.524326+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"1f80bb"},"request_uri":"http://127.0.0.1:8000/_wdt/1f80bb","method":"GET"} []
[2021-11-23T14:18:03.352582+01:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://127.0.0.1:8000/lucky/number","method":"GET"} []
[2021-11-23T14:18:03.361722+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-11-23T14:18:03.444828+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:18:03.691094+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"b733bf"},"request_uri":"http://127.0.0.1:8000/_wdt/b733bf","method":"GET"} []
[2021-11-23T14:28:39.000517+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:8000/ccount212/index.php"" at C:\Users\User\Documents\tsi_htmlworkshop\Topic 8\phpproject\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost:8000/ccount212/index.php\" at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/ccount212/index.php/\". at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:70)"} []
[2021-11-23T14:28:39.135178+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:28:39.137524+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:28:39.604794+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"df6fef"},"request_uri":"http://localhost:8000/_wdt/df6fef","method":"GET"} []
[2021-11-23T14:32:16.962017+01:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://127.0.0.1:8000/lucky/number","method":"GET"} []
[2021-11-23T14:32:16.973257+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-11-23T14:32:17.069751+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:32:17.352803+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"0ce436"},"request_uri":"http://127.0.0.1:8000/_wdt/0ce436","method":"GET"} []
[2021-11-23T14:35:25.863572+01:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://127.0.0.1:8000/lucky/number","method":"GET"} []
[2021-11-23T14:35:25.870222+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-11-23T14:35:25.931066+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:35:26.481578+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"4e55ff"},"request_uri":"http://127.0.0.1:8000/_wdt/4e55ff","method":"GET"} []
[2021-11-23T14:37:27.851705+01:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://127.0.0.1:8000/lucky/number","method":"GET"} []
[2021-11-23T14:37:27.870942+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-11-23T14:37:28.019063+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:37:28.482516+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"24a5a3"},"request_uri":"http://127.0.0.1:8000/_wdt/24a5a3","method":"GET"} []
[2021-11-23T14:37:31.024937+01:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://127.0.0.1:8000/lucky/number","method":"GET"} []
[2021-11-23T14:37:31.045471+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-11-23T14:37:31.213841+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:37:31.653768+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"b5237c"},"request_uri":"http://127.0.0.1:8000/_wdt/b5237c","method":"GET"} []
[2021-11-23T14:37:33.845644+01:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://127.0.0.1:8000/lucky/number","method":"GET"} []
[2021-11-23T14:37:33.864952+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-11-23T14:37:34.028057+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:37:34.498640+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"fb2fe7"},"request_uri":"http://127.0.0.1:8000/_wdt/fb2fe7","method":"GET"} []
[2021-11-23T14:37:44.084115+01:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://127.0.0.1:8000/lucky/number","method":"GET"} []
[2021-11-23T14:37:44.107192+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-11-23T14:37:44.237216+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:37:44.690623+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"20b7dd"},"request_uri":"http://127.0.0.1:8000/_wdt/20b7dd","method":"GET"} []
[2021-11-23T14:38:04.963835+01:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://127.0.0.1:8000/lucky/number","method":"GET"} []
[2021-11-23T14:38:04.982929+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-11-23T14:38:05.114716+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:38:05.579123+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"b69126"},"request_uri":"http://127.0.0.1:8000/_wdt/b69126","method":"GET"} []
[2021-11-23T14:39:04.373668+01:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://127.0.0.1:8000/lucky/number","method":"GET"} []
[2021-11-23T14:39:04.390927+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-11-23T14:39:04.535681+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:39:04.969654+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"b8a7ba"},"request_uri":"http://127.0.0.1:8000/_wdt/b8a7ba","method":"GET"} []
[2021-11-23T14:40:03.044187+01:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://127.0.0.1:8000/lucky/number","method":"GET"} []
[2021-11-23T14:40:03.058202+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-11-23T14:40:03.187168+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:40:03.742752+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"6713c7"},"request_uri":"http://127.0.0.1:8000/_wdt/6713c7","method":"GET"} []
[2021-11-23T14:40:45.759033+01:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://127.0.0.1:8000/lucky/number","method":"GET"} []
[2021-11-23T14:40:45.777850+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-11-23T14:40:45.914983+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:40:46.276375+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"a1d39a"},"request_uri":"http://127.0.0.1:8000/_wdt/a1d39a","method":"GET"} []
[2021-11-23T14:40:48.913663+01:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://127.0.0.1:8000/lucky/number","method":"GET"} []
[2021-11-23T14:40:48.928241+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-11-23T14:40:49.041879+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:40:49.381530+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"df2d2c"},"request_uri":"http://127.0.0.1:8000/_wdt/df2d2c","method":"GET"} []
[2021-11-23T14:41:30.639366+01:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://127.0.0.1:8000/lucky/number","method":"GET"} []
[2021-11-23T14:41:30.656027+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-11-23T14:41:30.784747+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:41:31.154423+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"60d168"},"request_uri":"http://127.0.0.1:8000/_wdt/60d168","method":"GET"} []
[2021-11-23T14:41:33.521788+01:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://127.0.0.1:8000/lucky/number","method":"GET"} []
[2021-11-23T14:41:33.532362+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-11-23T14:41:33.651220+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:41:34.034155+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"2ae32f"},"request_uri":"http://127.0.0.1:8000/_wdt/2ae32f","method":"GET"} []
[2021-11-23T14:41:35.612863+01:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://127.0.0.1:8000/lucky/number","method":"GET"} []
[2021-11-23T14:41:35.621875+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2021-11-23T14:41:35.722040+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\API\\PostgreSQL\\ExceptionConverter.php:83)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\User\\Documents\\tsi_htmlworkshop\\Topic 8\\phpproject\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
[2021-11-23T14:41:36.093225+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"a2a617"},"request_uri":"http://127.0.0.1:8000/_wdt/a2a617","method":"GET"} []
